# 开发环境配置
version: '3.8'

services:
  # 只启动必要的外部服务，应用在本地运行
  redis:
    image: redis:7-alpine
    container_name: base_agent_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    networks:
      - base_agent_dev_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: base_agent_elasticsearch_dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_dev_data:/usr/share/elasticsearch/data
    networks:
      - base_agent_dev_network

  etcd:
    container_name: milvus-etcd-dev
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_dev_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - base_agent_dev_network

  minio:
    container_name: milvus-minio-dev
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_dev_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    networks:
      - base_agent_dev_network

  milvus:
    container_name: milvus-standalone-dev
    image: milvusdb/milvus:v2.3.4
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_dev_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - base_agent_dev_network

  attu:
    container_name: milvus-attu-dev
    image: zilliz/attu:v2.3.8
    environment:
      MILVUS_URL: milvus:19530
    ports:
      - "8889:3000"
    depends_on:
      - "milvus"
    networks:
      - base_agent_dev_network

volumes:
  redis_dev_data:
  elasticsearch_dev_data:
  etcd_dev_data:
  minio_dev_data:
  milvus_dev_data:

networks:
  base_agent_dev_network:
    driver: bridge